### ISSUE TITLE
Add user info in Registration

### ISSUE THREAD

**Issue by rosoarv** [dev-tea-party/dev-access#21]
- add user information in registration
- refer to db table: users_info for the fields

**Comment by jandyl-casas** [comment]
check [access-21](https://github.com/dev-tea-party/dev-access/pull/33)

**Comment by rosoarv** [comment]
@jandyl-casas please see my comments on pr. kindly ask me if you have questions. thanks!

**Comment by jandyl-casas** [comment]
@rosoarv already push the new updates

**Comment by rosoarv** [comment]
@jandyl-casas great!

**Comment by jandyl-casas** [comment]
Done
