### ISSUE TITLE
CRUD: Materials Module

### ISSUE THREAD

**Issue by rosoarv** [dev-tea-party/dev-access#28]
- [x] Generate CRUD Operations for Materials Module
- [x] Update generated field labels and title
- [x] Connect Materials and Job Order (Add materials button in Job Order list)
- [x] Modify routes
- [x] Display materials based on Job Order
- [x] Set connected job order id as value of jo_id field
- [x] Hide job order id field
- [x] Implementation of search feature

**Comment by jandyl-casas** [comment]
Please check [access-28 Modify routes and display materials based on job order](https://github.com/dev-tea-party/dev-access/pull/45)

**Comment by jandyl-casas** [comment]
Please check newly commited updates. All iteration are done except search feature.

**Comment by jandyl-casas** [comment]
Please check newly committed updates. Code changes as per code review.

**Comment by jandyl-casas** [comment]
Please check newly committed updates. Code changes as per code review.

**Comment by jandyl-casas** [comment]
Please check newly committed updates. Materials module done.
