### ISSUE TITLE
Add font-awesome css

### ISSUE THREAD

**Issue by rosoarv** [dev-tea-party/dev-access#29]
- [x] add font-awesome in ./public/fonts/font-awesome
- [x] add font-awesome link tag in layout.app.blade

**Comment by litocabornay** [comment]
added font-awesome css

please check [access-29](https://github.com/dev-tea-party/dev-access/tree/access-29)

**Comment by rosoarv** [comment]
@litocabornay please see my comment on the pr. thanks!
