### ISSUE TITLE
Add Iteration 1 module links on sidebar

### ISSUE THREAD

**Issue by rosoarv** [dev-tea-party/dev-access#37]
- [x] Label sidebar as Navigation
- [x] Projects
- [x] Job Orders
- [x] Supplier Categories
- [x] Suppliers

**Comment by shernaleeuy** [comment]
working on this...

**Comment by shernaleeuy** [comment]
DONE!!

**Comment by shernaleeuy** [comment]
done working on this. kindly check [access-37](https://github.com/dev-tea-party/dev-access/pull/44)

**Comment by rosoarv** [comment]
@shernaleeuy nice!
